package mihon.core.migration.migrations

import mihon.core.migration.Migration

val migrations: List<Migration>
    get() = listOf(
        SetupBackupCreateMigration(),
        SetupLibraryUpdateMigration(),
        SetupEHentaiUpdateMigration(),
        SetupSyncDataMigration(),
        DelegateHBrowseMigration(),
        DelegateNHentaiMigration(),
        MergedMangaRewriteMigration(),
        LogoutFromMALMigration(),
        MoveDOHSettingMigration(),
        ResetRotationSettingMigration(),
        ResetReaderSettingsMigration(),
        DeleteOldMangaDexTracksMigration(),
        RemoveOldReaderThemeMigration(),
        RemoveShorterLibraryUpdatesMigration(),
        MoveLibrarySortingSettingsMigration(),
        RemoveShortLibraryUpdatesMigration(),
        MoveLibraryNonCompleteSettingMigration(),
        DeleteOldEhFavoritesDatabaseMigration(),
        MoveSecureScreenSettingMigration(),
        ChangeMiuiExtensionInstallerMigration(),
        MoveCoverOnlyGridSettingMigration(),
        MoveCatalogueCoverOnlyGridSettingMigration(),
        MoveLatestToFeedMigration(),
        MoveReaderTapSettingMigration(),
        MoveSortingModeSettingsMigration(),
        MoveSortingModeSettingMigration(),
        AlwaysBackupMigration(),
        ResetFilterAndSortSettingsMigration(),
        ChangeThemeModeToUppercaseMigration(),
        MoveReadingButtonSettingMigration(),
        ChangeTrackingQueueTypeMigration(),
        LogoutFromMangaDexMigration(),
        RemoveUpdateCheckerJobsMigration(),
        RemoveBatteryNotLowRestrictionMigration(),
        MoveRelativeTimeSettingMigration(),
        ClearBrokenPagePreviewCacheMigration(),
        MoveSettingsToPrivateOrAppStateMigration(),
        MoveExtensionRepoSettingsMigration(),
        MoveCacheToDiskSettingMigration(),
        MoveEncryptionSettingsToAppStateMigration(),
        TrustExtensionRepositoryMigration(),
    )
