blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://devil6venom.github.io/Comick/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🖥️ Comicks website
    url: https://devil6venom.github.io/Comick/
    about: Guides, troubleshooting, and answers to common questions
