package exh.eh.tags

object Artist3 : TagList {
    override fun getTags1(): List<String> = listOf(
        "artist:yuuki sonisuke",
        "artist:yuuki tomoka",
        "artist:yuuki tsumugi",
        "artist:yuuki yu",
        "artist:yuukis",
        "artist:yuumi kazuaki",
        "artist:yuunagi seshina",
        "artist:yuurei makomo",
        "artist:yuusa riki",
        "artist:yuusei iori",
        "artist:yuushi tessen",
        "artist:yuutsu",
        "artist:yuuzu tsushiro",
        "artist:yuxiang chen",
        "artist:yuyu",
        "artist:yuyu tamako",
        "artist:yuzhe s",
        "artist:yuzhou",
        "artist:yuzu kiro",
        "artist:yuzu ramune",
        "artist:yuzucky",
        "artist:yuzuki",
        "artist:yuzuki hikaru",
        "artist:yuzuki makii",
        "artist:yuzuki n dash",
        "artist:yuzuki neko",
        "artist:yuzuki ryota",
        "artist:yuzuki yua",
        "artist:yuzumi yu",
        "artist:yuzuno kiichi",
        "artist:yuzupoco",
        "artist:yuzupon",
        "artist:yuzuriha",
        "artist:yuzushiko",
        "artist:yves chaland",
        "artist:yyda potato",
        "artist:yykuaixian",
        "artist:z equal bouya",
        "artist:z equals bouya",
        "artist:zaagn",
        "artist:zabish",
        "artist:zabuton no uragawa",
        "artist:zackary911",
        "artist:zaha torute",
        "artist:zaki zaraki",
        "artist:zako",
        "artist:zamdin",
        "artist:zanfadar",
        "artist:zangi",
        "artist:zankuro",
        "artist:zanzi",
        "artist:zanzim",
        "artist:zaou taishi",
        "artist:zarathul",
        "artist:zaribot",
        "artist:zaunderground",
        "artist:zawar",
        "artist:zdl",
        "artist:zea lark",
        "artist:zeblackballd",
        "artist:zebodoy",
        "artist:zeekzag",
        "artist:zefrableu",
        "artist:zegga",
        "artist:zekky monzz",
        "artist:zekkyosyu",
        "artist:zeklullaby",
        "artist:zel",
        "artist:zelhypno",
        "artist:zen cross",
        "artist:zen migawa",
        "artist:zenbaymono studio",
        "artist:zenchi",
        "artist:zennith mehathvin",
        "artist:zeno",
        "artist:zenosuke",
        "artist:zenshingu",
        "artist:zephid",
        "artist:zephypotato",
        "artist:zepie",
        "artist:zeplich",
        "artist:zerbebuth",
        "artist:zerg",
        "artist:zero punch",
        "artist:zero tanuki",
        "artist:zero130",
        "artist:zerocat",
        "artist:zerogravitas",
        "artist:zeromccall",
        "artist:zeros",
        "artist:zeroshiki aria",
        "artist:zeroshiki kouichi",
        "artist:zerotwo",
        "artist:zestysauce",
        "artist:zet13",
        "artist:zeta-haru",
        "artist:zetomeso",
        "artist:zetu red",
        "artist:zetumame",
        "artist:zhajiangmian mm",
        "artist:zhen lu",
        "artist:zheng",
        "artist:zhengda",
        "artist:zhf 531",
        "artist:zhi yitiaomiao",
        "artist:zhicun zhengyi",
        "artist:zi",
        "artist:zicker",
        "artist:ziemniax",
        "artist:zigrock",
        "artist:ziko",
        "artist:zinan",
        "artist:zinen",
        "artist:zingate",
        "artist:zirahu manbou",
        "artist:ziroko",
        "artist:ziz",
        "artist:zizi",
        "artist:zlfnrk",
        "artist:zogok.",
        "artist:zoh",
        "artist:zoidberg656",
        "artist:zol",
        "artist:zoma",
        "artist:zone",
        "artist:zonebell tsukiji",
        "artist:zonkpunch",
        "artist:zonta",
        "artist:zoological",
        "artist:zootan",
        "artist:zorglube",
        "artist:zorigan",
        "artist:zorro re",
        "artist:zouzou",
        "artist:zro5um",
        "artist:zukiki",
        "artist:zundarepon",
        "artist:zuo jiu ye",
        "artist:zurikat",
        "artist:zuririan",
        "artist:zutto mae kara darui.",
        "artist:zwesomerachel",
        "artist:zwwilzza",
        "artist:zxc338093",
        "artist:zyaroh akira",
        "artist:zyd",
    )
}
