package exh.eh.tags

object Group2 : TagList {
    override fun getTags1(): List<String> = listOf(
        "group:valkyrieharlem",
        "group:vanilla fuumi shoujo",
        "group:vanilla star",
        "group:vanilla-dou max",
        "group:variety pot",
        "group:vashadow",
        "group:vc productions",
        "group:venom",
        "group:veronica no ha",
        "group:violence asia team",
        "group:visual biscuits",
        "group:vitamin gohan",
        "group:vitamin soft",
        "group:vitamin x",
        "group:vivi-sectr",
        "group:vivid color",
        "group:vivid dot",
        "group:vivido",
        "group:viweb",
        "group:voltcompany.",
        "group:vpans extasy",
        "group:vulcannu",
        "group:w at nd",
        "group:wabi sabi wasabi",
        "group:wagamama dou",
        "group:wakaba syokei",
        "group:wakarase seisaku iinkai",
        "group:wakatobi",
        "group:wakusei-teki shukou",
        "group:wakuwaku boycott",
        "group:wakuwaku doubutsuen",
        "group:walhalla illusion",
        "group:wamusho",
        "group:wanko-tei",
        "group:wankyoku canvas",
        "group:wanwandoh",
        "group:warabimochi",
        "group:waretama",
        "group:warp loop",
        "group:wasa wasa",
        "group:washikul.",
        "group:washokudeniku.",
        "group:wata 120 percent",
        "group:wataame",
        "group:watagashi maker",
        "group:watanabe tou",
        "group:wataru kuya",
        "group:water ducts",
        "group:waterfall",
        "group:waterspoon",
        "group:waterstudio",
        "group:waterwheel",
        "group:weather report",
        "group:webstudioofflimits",
        "group:wellca",
        "group:wendybell",
        "group:west vision",
        "group:whirl-wind",
        "group:white out",
        "group:white plus dk",
        "group:white rocket",
        "group:whitecloth",
        "group:whitesoft",
        "group:whitewill",
        "group:wi-fe hacker",
        "group:wicked heart",
        "group:wild goat",
        "group:will tame",
        "group:willow soft",
        "group:wind mail",
        "group:wind of the keep valley",
        "group:windarteam",
        "group:winger in mind",
        "group:winghills",
        "group:wish",
        "group:wish kibou no tsubasa",
        "group:witchflame",
        "group:witching hour entertainment",
        "group:wizard",
        "group:wolf fang dou",
        "group:wonderland 203",
        "group:wope-retta",
        "group:world of porncraft",
        "group:world temperament",
        "group:worstworks",
        "group:wriggle souzeme tomonokai",
        "group:x model",
        "group:x-tei",
        "group:xephs artwork",
        "group:xl-toons",
        "group:xx koubou",
        "group:xxxxxxx",
        "group:xyzyroh",
        "group:y slash s slash k",
        "group:y.d.l",
        "group:y.m.sensha",
        "group:yaboudo project",
        "group:yabougumi",
        "group:yabukaradou",
        "group:yaburi dokoro",
        "group:yadapot",
        "group:yadokugaeru",
        "group:yadoo van yahdoo",
        "group:yagi q-syah",
        "group:yago no ana",
        "group:yajilshi plus",
        "group:yajirushi key",
        "group:yajiya",
        "group:yakata",
        "group:yakimisomura",
        "group:yakinasu teishoku",
        "group:yakiniku teishoku",
        "group:yakisaketeishoku",
        "group:yakisoba pants",
        "group:yakisoba rengo",
        "group:yakiubu",
        "group:yakousei fan club",
        "group:yaku 40 man sarad",
        "group:yakumi sarai",
        "group:yakusyo",
        "group:yakutai",
        "group:yam x 2 dai teikoku",
        "group:yamada ichizoku.",
        "group:yamadamaya",
        "group:yamadaya",
        "group:yamagiwa art cg studio",
        "group:yamaguchirou",
        "group:yamakawa denenhuukei",
        "group:yamami no yado",
        "group:yamamori gohan",
        "group:yamanaka no naka",
        "group:yamano murao",
        "group:yamato nadeshiko club",
        "group:yami ni ugomeku",
        "group:yamikumo tsuushin",
        "group:yamotodou rakugakiichi",
        "group:yanagiba dai",
        "group:yanagisegawa",
        "group:yanasegawabeya",
        "group:yangyang nickbow",
        "group:yanmarumaa",
        "group:yaou keikaku",
        "group:yaoyorozu-kobo",
        "group:yaoyorozudo",
        "group:yasai batake",
        "group:yaseuma lo-ru",
        "group:yashiya",
        "group:yashock kaigi",
        "group:yasrin-do",
        "group:yasudajuku",
        "group:yasuomi-craft",
        "group:yasyokutei",
        "group:yatomomin",
        "group:yatuumi no kagami",
        "group:yawaraka okashiya",
        "group:yaya hinata-ya",
        "group:yes sir.",
        "group:yggdrasil",
        "group:yo-metdo",
        "group:yoban left",
        "group:yobigakka",
        "group:yohsyuan",
        "group:yojouhan factory",
        "group:yojouhan shobou",
        "group:yojouhan toshi",
        "group:yokan musume",
        "group:yokazetei",
        "group:yokohama zza koubou",
        "group:yokoshimanchi.",
        "group:yokoshimaya",
        "group:yokoshoku ice",
        "group:yoku mireba beta",
        "group:yomamagoto",
        "group:yomosue doukoukai",
        "group:yomothuhirasaka",
        "group:yonatan black mutou",
        "group:yonbangai garo",
        "group:yonjuichi",
        "group:yonmasuya",
        "group:yonurime",
        "group:yorando",
        "group:yoru no benkyoukai",
        "group:yoru no okazu shokudou",
        "group:yoruyama no kyuukeijo",
        "group:yoseatume tekina nanika",
        "group:yoshida gorou shoukai",
        "group:yoshiga dokoro",
        "group:yoshii tech sha",
        "group:yotukuro",
        "group:you",
        "group:you you tsuushin",
        "group:you you you",
        "group:youchi-na-ochakai",
        "group:youen bijo no garou",
        "group:yougensya",
        "group:youkai ankake",
        "group:youkai tamanokoshi",
        "group:youkandou",
        "group:youki m.k.c.",
        "group:youmusya",
        "group:yours-wow",
        "group:yousei allergen",
        "group:youseimangasya",
        "group:youtoujirushi",
        "group:youtsuu transmitter",
        "group:youyukai",
        "group:yowatari kouba",
        "group:yoyude ikemasu",
        "group:yozorairodrops",
        "group:ys company",
        "group:yu-ta.18",
        "group:yu-yu-tei",
        "group:yuasa rengou",
        "group:yubidou",
        "group:yudenakya nama-beer",
        "group:yudokuya",
        "group:yuhshiki",
        "group:yukagenikaga",
        "group:yukan high zakura",
        "group:yukeyuke ryuseigo",
        "group:yuki daruma koujou",
        "group:yuki no iori",
        "group:yukijirushi nyuugyou",
        "group:yukikagerou",
        "group:yukimi honpo",
        "group:yukimura",
        "group:yukinko okeya",
        "group:yukino koubou",
        "group:yukirinrin",
        "group:yukyu-kyuka",
        "group:yume bouei shoujo tai",
        "group:yume yori suteki na",
        "group:yume-zakura",
        "group:yumeiro-goromo",
        "group:yumeizukosya",
        "group:yumemigachi campus",
        "group:yumemigokoti",
        "group:yumemiru-kikai",
        "group:yumenamakon",
        "group:yumenokage",
        "group:yumeoikyounouta",
        "group:yumeoukoku",
        "group:yunabon",
        "group:yurayuraseyuura",
        "group:yureika blade",
        "group:yuri dokidoki",
        "group:yuri equal 18l",
        "group:yuriai kojinshi kai",
        "group:yurinyurin",
        "group:yuriru-rarika",
        "group:yurumebox",
        "group:yuruyakatou",
        "group:yuruyuru seisakusho",
        "group:yusuzumi",
        "group:yuu adashino suisan",
        "group:yuu heya",
        "group:yuubin basha",
        "group:yuudachitei",
        "group:yuuendou",
        "group:yuugai tosho kikaku",
        "group:yuugen kaisha sokuhou seisakusho",
        "group:yuugensangyou sukimakaze",
        "group:yuugure koubou",
        "group:yuuhodou",
        "group:yuujikouji",
        "group:yuukakumin",
        "group:yuuki kagoubutsu",
        "group:yuukyuu shinden",
        "group:yuukyuu suisenkan",
        "group:yuunagi gaibutai",
        "group:yuuriko",
        "group:yuusha kandenchi",
        "group:yuutopia",
        "group:yuuya-yuu",
        "group:yuyake box",
        "group:yuzu soft",
        "group:yuzucha",
        "group:yuzuen",
        "group:yuzumomo jam",
        "group:yuzuonsen",
        "group:yuzuponz",
        "group:yuzurihaya",
        "group:z",
        "group:z-tabukuroneko house",
        "group:z-vector",
        "group:za da carjya",
        "group:zakkin kougyou",
        "group:zan-sei",
        "group:zankirow",
        "group:zankoku doumei",
        "group:zankoku na kami ga shihai suru",
        "group:zantetuken",
        "group:zasshu-ken",
        "group:zassoubatake",
        "group:zassoya",
        "group:zatouichi",
        "group:zatuyou gakari",
        "group:zawameki jambo",
        "group:zeiniku shoujotai",
        "group:zenmai koubou",
        "group:zenmai kourogi",
        "group:zennihon do-m jitsuryoku kentei kousa",
        "group:zenoside",
        "group:zenra restaurant",
        "group:zenryoku sissou cat",
        "group:zensekai yakenohara doumei",
        "group:zenshuu bougyo",
        "group:zensoku zenkai.",
        "group:zensun habaku",
        "group:zenzidou kosyubenjo",
        "group:zero byte",
        "group:zero equals mono",
        "group:zero ni kaeru tsuki",
        "group:zero-one",
        "group:zero-sen",
        "group:zero-xx",
        "group:zerocool",
        "group:zeroinfinityone",
        "group:zeryishi",
        "group:zettai shoujo",
        "group:zettaitensei",
        "group:zgf",
        "group:zi",
        "group:zion",
        "group:zmey no soukutsu",
        "group:zokubutsu.zip",
        "group:zombie to yukaina nakamatachi",
        "group:zonzon sharp 4",
        "group:zooerastia",
        "group:zouri no sato",
        "group:zozalist",
        "group:zugaikotsu marudashi",
        "group:zvizva-dan",
        "group:zydan",
        "group:zyulokuya",
        "group:zzz comics",
    )
}
