package exh.eh.tags

object Language : TagList {
    override fun getTags1() = listOf(
        "language:arabic",
        "language:bulgarian",
        "language:catalan",
        "language:cebuano",
        "language:chinese",
        "language:cree",
        "language:creole",
        "language:czech",
        "language:danish",
        "language:dutch",
        "language:english",
        "language:finnish",
        "language:french",
        "language:german",
        "language:greek",
        "language:hindi",
        "language:hungarian",
        "language:indonesian",
        "language:irish",
        "language:italian",
        "language:japanese",
        "language:korean",
        "language:ladino",
        "language:lao",
        "language:norwegian",
        "language:persian",
        "language:polish",
        "language:portuguese",
        "language:rewrite",
        "language:romanian",
        "language:russian",
        "language:sango",
        "language:spanish",
        "language:speechless",
        "language:swedish",
        "language:tagalog",
        "language:text cleaned",
        "language:thai",
        "language:tigrinya",
        "language:translated",
        "language:turkish",
        "language:vietnamese",
        "language:zulu",
    )
}
