package exh.eh.tags

object Male : TagList {

    override fun getTags1() = listOf(
        "male:abortion",
        "male:absorption",
        "male:age progression",
        "male:age regression",
        "male:ahegao",
        "male:alien",
        "male:amputee",
        "male:anal",
        "male:anal birth",
        "male:anal intercourse",
        "male:anal prolapse",
        "male:angel",
        "male:animal on furry",
        "male:animegao",
        "male:apparel bukkake",
        "male:apron",
        "male:armpit licking",
        "male:asphyxiation",
        "male:bald",
        "male:ball sucking",
        "male:balls expansion",
        "male:bandages",
        "male:bat boy",
        "male:bbm",
        "male:bdsm",
        "male:bear",
        "male:bear boy",
        "male:bestiality",
        "male:big ass",
        "male:big balls",
        "male:big breasts",
        "male:big nipples",
        "male:big penis",
        "male:bike shorts",
        "male:bikini",
        "male:birth",
        "male:bisexual",
        "male:blackmail",
        "male:blind",
        "male:blindfold",
        "male:blood",
        "male:bloomers",
        "male:blowjob",
        "male:blowjob face",
        "male:body painting",
        "male:body swap",
        "male:body writing",
        "male:bodystocking",
        "male:bodysuit",
        "male:bondage",
        "male:breast feeding",
        "male:bride",
        "male:brother",
        "male:bukkake",
        "male:bull",
        "male:bunny boy",
        "male:burping",
        "male:business suit",
        "male:butler",
        "male:cannibalism",
        "male:cashier",
        "male:cat",
        "male:catboy",
        "male:cbt",
        "male:cervix prolapse",
        "male:chastity belt",
        "male:cheating",
        "male:cheerleader",
        "male:chikan",
        "male:chinese dress",
        "male:chloroform",
        "male:christmas",
        "male:clit stimulation",
        "male:clone",
        "male:clothed female nude male",
        "male:coach",
        "male:cock ring",
        "male:collar",
        "male:condom",
        "male:coprophagia",
        "male:corruption",
        "male:corset",
        "male:cosplaying",
        "male:cousin",
        "male:cowman",
        "male:crab",
        "male:crossdressing",
        "male:crown",
        "male:cuntboy",
        "male:dark nipples",
        "male:dark sclera",
        "male:dark skin",
        "male:deepthroat",
        "male:deer",
        "male:demon",
        "male:dick growth",
        "male:dickgirl on male",
        "male:dilf",
        "male:dinosaur",
        "male:dog",
        "male:dog boy",
        "male:donkey",
        "male:double anal",
        "male:double blowjob",
        "male:double penetration",
        "male:dougi",
        "male:dragon",
        "male:drill hair",
        "male:drugs",
        "male:drunk",
        "male:eel",
        "male:eggs",
        "male:electric shocks",
        "male:elephant",
        "male:elf",
        "male:emotionless sex",
        "male:enema",
        "male:exhibitionism",
        "male:exposed clothing",
        "male:eye penetration",
        "male:eye-covering bang",
        "male:eyemask",
        "male:eyepatch",
        "male:facial hair",
        "male:fairy",
        "male:farting",
        "male:father",
        "male:feminization",
        "male:filming",
        "male:first person perspective",
        "male:fish",
        "male:fishnets",
        "male:fisting",
        "male:focus paizuri",
        "male:food on body",
        "male:foot licking",
        "male:footjob",
        "male:forniphilia",
        "male:fox",
        "male:fox boy",
        "male:freckles",
        "male:frog",
        "male:frottage",
        "male:fundoshi",
        "male:furry",
        "male:gag",
        "male:gaping",
        "male:garter belt",
        "male:gasmask",
        "male:gender change",
        "male:gender morph",
        "male:ghost",
        "male:giant",
        "male:glasses",
        "male:glory hole",
        "male:goblin",
        "male:gokkun",
        "male:gorilla",
        "male:gothic lolita",
        "male:grandfather",
        "male:group",
        "male:growth",
        "male:guro",
        "male:gyaru-oh",
        "male:gymshorts",
        "male:hair buns",
        "male:hairy",
        "male:handjob",
        "male:harem",
        "male:harpy",
        "male:headphones",
        "male:horns",
        "male:horse",
        "male:horse boy",
        "male:horse cock",
        "male:hotpants",
        "male:human on furry",
        "male:humiliation",
        "male:impregnation",
        "male:incest",
        "male:infantilism",
        "male:inflation",
        "male:insect",
        "male:insect boy",
        "male:invisible",
        "male:josou seme",
        "male:kemonomimi",
        "male:kigurumi pajama",
        "male:kimono",
        "male:kissing",
        "male:lab coat",
        "male:large insertions",
        "male:large tattoo",
        "male:latex",
        "male:layer cake",
        "male:leotard",
        "male:lingerie",
        "male:lion",
        "male:lizard guy",
        "male:long tongue",
        "male:low bestiality",
        "male:low shotacon",
        "male:machine",
        "male:maggot",
        "male:magical girl",
        "male:maid",
        "male:makeup",
        "male:males only",
        "male:masked face",
        "male:masturbation",
        "male:merman",
        "male:mesuiki",
        "male:metal armor",
        "male:midget",
        "male:miko",
        "male:military",
        "male:mind break",
        "male:mind control",
        "male:miniguy",
        "male:minotaur",
        "male:monkey",
        "male:monkey boy",
        "male:monster",
        "male:moral degeneration",
        "male:mouse",
        "male:mouse boy",
        "male:multiple assjob",
        "male:multiple footjob",
        "male:multiple handjob",
        "male:multiple orgasms",
        "male:multiple penises",
        "male:muscle",
        "male:nakadashi",
        "male:necrophilia",
        "male:netorare",
        "male:ninja",
        "male:nipple birth",
        "male:nose fuck",
        "male:nose hook",
        "male:nun",
        "male:nurse",
        "male:octopus",
        "male:oil",
        "male:old man",
        "male:onahole",
        "male:orc",
        "male:orgasm denial",
        "male:otokofutanari",
        "male:paizuri",
        "male:panther",
        "male:pantyhose",
        "male:pasties",
        "male:pegging",
        "male:penis birth",
        "male:petplay",
        "male:phimosis",
        "male:piercing",
        "male:pig",
        "male:pig man",
        "male:pillory",
        "male:piss drinking",
        "male:plant boy",
        "male:pole dancing",
        "male:policeman",
        "male:possession",
        "male:pregnant",
        "male:priest",
        "male:prolapse",
        "male:prostate massage",
        "male:prostitution",
        "male:pubic stubble",
        "male:public use",
        "male:rabbit",
        "male:randoseru",
        "male:rape",
        "male:reptile",
        "male:rhinoceros",
        "male:rimjob",
        "male:robot",
        "male:ryona",
        "male:scar",
        "male:scat",
        "male:school gym uniform",
        "male:school swimsuit",
        "male:schoolboy uniform",
        "male:schoolgirl uniform",
        "male:selfcest",
        "male:sex toys",
        "male:shared senses",
        "male:shark",
        "male:shark boy",
        "male:sheep",
        "male:sheep boy",
        "male:shibari",
        "male:shimapan",
        "male:shotacon",
        "male:shrinking",
        "male:skinsuit",
        "male:slave",
        "male:sleeping",
        "male:slime",
        "male:slime boy",
        "male:slug",
        "male:small penis",
        "male:smegma",
        "male:smell",
        "male:smoking",
        "male:snake",
        "male:snake boy",
        "male:snuff",
        "male:sole male",
        "male:solo action",
        "male:spanking",
        "male:speculum",
        "male:spider",
        "male:squid boy",
        "male:stewardess",
        "male:stockings",
        "male:stomach deformation",
        "male:stretching",
        "male:stuck in wall",
        "male:sundress",
        "male:sunglasses",
        "male:sweating",
        "male:swimsuit",
        "male:swinging",
        "male:syringe",
        "male:tail",
        "male:tail plug",
        "male:tall man",
        "male:tanlines",
        "male:teacher",
        "male:tentacles",
        "male:thigh high boots",
        "male:tiara",
        "male:tickling",
        "male:tiger",
        "male:tights",
        "male:toddlercon",
        "male:tomgirl",
        "male:tooth brushing",
        "male:torture",
        "male:tracksuit",
        "male:trampling",
        "male:transformation",
        "male:tube",
        "male:turtle",
        "male:tutor",
        "male:twins",
        "male:unbirth",
        "male:uncle",
        "male:unicorn",
        "male:unusual pupils",
        "male:urethra insertion",
        "male:urination",
        "male:vampire",
        "male:very long hair",
        "male:virginity",
        "male:vomit",
        "male:vore",
        "male:voyeurism",
        "male:waiter",
        "male:waitress",
        "male:whip",
        "male:wings",
        "male:witch",
        "male:wolf",
        "male:wolf boy",
        "male:wooden horse",
        "male:worm",
        "male:wormhole",
        "male:x-ray",
        "male:yandere",
        "male:yaoi",
    )
}
