package exh.eh.tags

object Other : TagList {

    override fun getTags1() = listOf(
        "other:3d",
        "other:already uploaded",
        "other:anaglyph",
        "other:animated",
        "other:anthology",
        "other:artbook",
        "other:caption",
        "other:comic",
        "other:compilation",
        "other:dakimakura",
        "other:figure",
        "other:forbidden content",
        "other:full censorship",
        "other:full color",
        "other:game sprite",
        "other:goudoushi",
        "other:hardcore",
        "other:how to",
        "other:incomplete",
        "other:missing cover",
        "other:mosaic censorship",
        "other:multi-work series",
        "other:multipanel sequence",
        "other:no penetration",
        "other:non-h imageset",
        "other:non-nude",
        "other:novel",
        "other:nudity only",
        "other:out of order",
        "other:paperchild",
        "other:poor grammar",
        "other:realporn",
        "other:redraw",
        "other:replaced",
        "other:rough translation",
        "other:sample",
        "other:scanmark",
        "other:screenshots",
        "other:sketch lines",
        "other:stereoscopic",
        "other:story arc",
        "other:tankoubon",
        "other:themeless",
        "other:time stop",
        "other:uncensored",
        "other:variant set",
        "other:watermarked",
        "other:webtoon",
        "other:western cg",
        "other:western imageset",
        "other:western non-h",
        "other:yukkuri",
    )
}
