name: Update website

on:
  release:
    types:
      - published
      - deleted
      - edited

jobs:
  update_website:
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Update website on release
        uses: benc-uk/workflow-dispatch@31e2b3319479a63f0ab15bf800eff9e913504e26 # v1.3.2
        with:
          workflow: Deploy
          repo: komikku-app/komikku-app.github.io
          ref: "refs/heads/main"
          token: "${{ secrets.BOT_PAT }}"
